### PR TITLE
Updated Unit-Tests to NUnit 3.2.1 and FluentAssertions 4.6.3

### PR DESCRIPTION
**Pull request by x0nn**
- Replaced ExpectedException with Assert.That
- Removed ExpectedMessage because of Problems with different languages

### CODE REVIEW

**Comment by cyotek** [comment]
Hello,

Thanks for the contribution. While the changes you have made won't affect this project right now, I don't like losing the exception text as frequently you might throw the same exception with different text (e.g. multiple `ArgumentException` for different parameters). I wonder how you are actually supposed to test in this case. (Or how you are supposed to test localized error messages in the first place). I haven't thought about localized testing before.

Thanks again for the contribution!

Regards;
Richard Moss

**Comment by x0nn** [comment]
Hi,

thanks for merging. The text could be used easily with adding:

.With.Message.EqualTo("The new capacity must be greater than or equal to the buffer size.\r\nParameter name: value\r\nActual value was 3."));

but when there are different localisations of the message it will be painful to check ("Actual value was ...." is localized by .NET to i.e. "Der tatsächliche Wert war ..."). Therefore I deleted it. In my opinion it is unlikely that one of these Tests will go red and the other not. Therefore you will see, that it is an error "more down the rabbithole".

I would like to add EventHandlers to the CircularBuffer (Changed and Full) to use the Buffer for a project and Exceptions in different language (german in particular). . Do you have any objections?

Regards
David

**Comment by cyotek** [comment]
Hello,

I don't mind the events, but I'm not so sure on the localization as I assume it will mean a bunch of extra satellite DLL's which seems a bit overkill for such a simple lib (especially as by their very nature we shouldn't see the exceptions). I'd probably do it as two different PR's so it's easy to handle if we decided against either one of them. Regardless though, feel free to submit them!

Thanks;
Richard Moss

**Comment by x0nn** [comment]
Hi,

youre right with the dependencies. Its not important. I'll just add the events.

Regards
David

**Pull request merged**
